### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by FooBen100** [Official-Husko/holehouse-better-cheats#2]
it didn't put enough detail in and i can't figure out how to get it to work.

**Comment by Official-Husko** [comment]
Sure thing,

Make sure you got the prerequisites:
- [Latest Game](https://f95zone.to/threads/holehouse-v0-1-62-patreon-dotart.99037/)
- [BepInEx 5](https://github.com/BepInEx/BepInEx/releases/download/v5.4.22/BepInEx_x64_5.4.22.0.zip)
- [Latest Mod](https://github.com/Official-Husko/HoleHouse-Better-Cheats/releases/latest) (mod_menu.zip)

Installation:
1. Unpack the downloaded game. [Image](https://i.imgur.com/hcfSUlg.png)
2. Install BepInEx (Throw all the files from the zip into the game folder where the exe is). [Gif](https://i.imgur.com/OggABhh.gif)
3. Start the game once to generate the necessary files.
4. install the **better_cheats.dll** into **BepInEx/plugins** in the game folder. [Gif](https://i.imgur.com/RFD3nl9.gif)
5. Launch the game and look for a mod menu button. [Image](https://i.imgur.com/SVPiZ0E.png)

**_If this resolved your issue please close it. If you have any other questions or issues feel free to ask._**

**Comment by Official-Husko** [comment]
i consider this issue resolved. If this is a mistake please comment on this issue again or open a new one.
